#!/usr/bin/env node
/**
 * Regenerates docs/spec/requirements.md from the requirement anchors in docs/spec/NN-*.md
 * (lines starting with <a id="XXX-NN"></a>**[XXX-NN]**). A test fails when the file is out of date.
 *   node scripts/spec-index.mjs          write docs/spec/requirements.md
 *   node scripts/spec-index.mjs --check  exit 1 if it would change
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SPEC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../docs/spec');
const GROUP = {
  LM: 'Logical model', EXT: 'Extensions', LNK: 'Video links', ST: 'Storage', SH: 'Shards', OV: 'Overlays', ID: 'Identity', DU: 'Duplicates',
  PK: 'Position keys', NO: 'Normalization', IX: 'Indexes', CL: 'Client', SE: 'Search', EAS: 'Ease of contribution', CTB: 'Contribution paths',
  ATT: 'Companion files and attachments', VA: 'Validation', FB: 'Feedback', MP: 'Merge policy', IN: 'Ingestion', CR: 'Corrections', RC: 'Recognition',
  ILL: 'Illegal plays made in real matches', RPL: 'Replay', SC: 'Security', ME: 'Metrics', RP: 'Rights and privacy', EV: 'Evolution', HST: 'Hosting',
};

export function listRequirements() {
  const files = fs.readdirSync(SPEC).filter((f) => /^\d\d-.*\.md$/.test(f) && !f.startsWith('90-')).sort();
  const out = [];
  for (const f of files) {
    for (const line of fs.readFileSync(path.join(SPEC, f), 'utf8').split('\n')) {
      const m = line.match(/^<a id="([A-Z]+-\d+)"><\/a>\*\*\[\1\]\*\*\s*(.*)$/);
      if (m) out.push({ id: m[1], file: f, text: m[2] });
    }
  }
  return out;
}

const summary = (t) => {
  const s = t.replace(/\[\[([A-Z]+-\d+)\]\([^)]*\)/g, '[$1]').replace(/[*`\\]/g, '').replace(/\|/g, '\\|');
  return s.length > 140 ? `${s.slice(0, 140)}...` : s;
};

export function render(reqs = listRequirements()) {
  const groups = new Map();
  for (const r of reqs) { const p = r.id.split('-')[0]; if (!groups.has(p)) groups.set(p, []); groups.get(p).push(r); }
  const lines = ['> [bgdb](../../README.md) · [Documentation](../README.md) · BGDB specification, Part I · [Overview](README.md)', '', '# Requirements index', '',
    'Every numbered requirement of the specification, with the file that defines it. Keywords follow RFC 2119. This file is generated by `scripts/spec-index.mjs`; do not edit it by hand.', ''];
  for (const [p, items] of groups) {
    lines.push('', `## ${p} - ${GROUP[p] ?? p}`, '', '| ID | Summary |', '|---|---|');
    for (const r of items) lines.push(`| [${r.id}](${r.file}#${r.id}) | ${summary(r.text)} |`);
  }
  return `${lines.join('\n')}\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const target = path.join(SPEC, 'requirements.md');
  const next = render();
  if (process.argv.includes('--check')) {
    const same = fs.existsSync(target) && fs.readFileSync(target, 'utf8') === next;
    if (!same) console.error('docs/spec/requirements.md is out of date: run "node scripts/spec-index.mjs"');
    process.exitCode = same ? 0 : 1;
  } else {
    fs.writeFileSync(target, next);
    console.log(`${listRequirements().length} requirements written to docs/spec/requirements.md`);
  }
}
